name: Azure Login with OIDC

on:
  push:
    branches:
      - main  # Déclenchement sur push sur main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Se connecter à Azure via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          auth-type: IDENTITY
          audience: api://AzureADTokenExchange
          allow-no-subscriptions: true  # Permet de ne pas spécifier de subscription

      - name: Vérifier l'authentification
        run: echo "OIDC Authentification réussie"
