name: Azure Login with OIDC

on:
  push:
    branches:
      - main  # Déclenchement sur push sur main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Se connecter à Azure via OIDC
        run: |
          az login --identity --tenant ${{ secrets.AZURE_TENANT_ID }} --username ${{ secrets.AZURE_CLIENT_ID }} --audience api://AzureADTokenExchange
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          
      - name: Vérifier l'authentification
        run: echo "OIDC Authentification réussie"
